services:
  postgres-dev:
    image: postgres:16-alpine
    container_name: logistic-app-be-dev-db
    environment:
      POSTGRES_DB: logistic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-dev-data:/var/lib/postgresql/data

volumes:
  pg-dev-data:
